// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXkjV6hRyjc5382jogAYgJ4Cx0aubkqaE',
    appId: '1:567406708541:web:d0c1cc2ebfecdba210a754',
    messagingSenderId: '567406708541',
    projectId: 'movie-database-6d2a5',
    authDomain: 'movie-database-6d2a5.firebaseapp.com',
    storageBucket: 'movie-database-6d2a5.appspot.com',
    measurementId: 'G-LZ0ZMT7DV0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB59s5QGXIfyUzO4TuYcXG1_L7n0zWYwXw',
    appId: '1:567406708541:android:4362f04a14c168a210a754',
    messagingSenderId: '567406708541',
    projectId: 'movie-database-6d2a5',
    storageBucket: 'movie-database-6d2a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3cfBupajlsYwIscetv0ZrqrUMmyv0cII',
    appId: '1:567406708541:ios:1fc792f1afd2912310a754',
    messagingSenderId: '567406708541',
    projectId: 'movie-database-6d2a5',
    storageBucket: 'movie-database-6d2a5.appspot.com',
    iosClientId: '567406708541-gc5bb8rvrc02bk9f6logkloanrststkr.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3cfBupajlsYwIscetv0ZrqrUMmyv0cII',
    appId: '1:567406708541:ios:4a2ee345a4e589a910a754',
    messagingSenderId: '567406708541',
    projectId: 'movie-database-6d2a5',
    storageBucket: 'movie-database-6d2a5.appspot.com',
    iosClientId: '567406708541-t7dmodb9gqfvligh52jubojtq6i6u561.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieApp.RunnerTests',
  );
}
